---
- name: Установка Docker на группу app
  hosts: app
  become: yes
  tasks:
    - name: Установка Docker для Ubuntu
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Установка Docker для CentOS
      yum:
        name: docker
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Запуск и включение Docker
      service:
        name: docker
        state: started
        enabled: yes

- name: Установка PostgreSQL на группу database
  hosts: database
  become: yes
  vars:
    postgres_version: "{{ postgres_version }}"
    data_dir: "{{ data_dir }}"
  
  tasks:
    - name: Установка PostgreSQL
      apt:
        name: "postgresql-{{ postgres_version }}"
        state: present
        update_cache: yes

    - name: Создание data-директории
      file:
        path: "{{ data_dir }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Настройка data-директории в конфиге
      lineinfile:
        path: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
        regexp: '^data_directory ='
        line: "data_directory = '{{ data_dir }}'"
        backup: yes
      notify: restart postgresql

  handlers:
    - name: restart postgresql
      service:
        name: postgresql
        state: restarted
